package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Category;
import ba.unsa.etf.rpr.exceptions.QuoteException;

import java.util.List;

public class CategoryManager {

    public void validateCategoryName(String name) throws QuoteException{
        if (name == null || name.length() > 45 || name.length() < 3){
            throw new QuoteException("Category name must be between 3 and 45 chars");
        }
    }
    public Category add(Category cat) throws QuoteException {
        if (cat.getId() != 0){
            throw new QuoteException("Can't add category with ID. ID is autogenerated");
        }
        validateCategoryName(cat.getName());

        try{
            return DaoFactory.categoryDao().add(cat);
        }catch (QuoteException e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new QuoteException("Category with same name exists");
            }
            throw e;
        }
    }

    public void delete(int categoryId) throws QuoteException{
        try{
            DaoFactory.categoryDao().delete(categoryId);
        }catch (QuoteException e){
            if (e.getMessage().contains("FOREIGN KEY")){
                throw new QuoteException("Cannot delete category which is related to quotes. First delete related quotes before deleting category.");
            }
            throw e;
        }

    }

    public Category update(Category cat) throws QuoteException{
        validateCategoryName(cat.getName());
        return DaoFactory.categoryDao().update(cat);
    }

    public List<Category> getAll() throws QuoteException{
        return DaoFactory.categoryDao().getAll();
    }

}
